(function(){
  const D={
    de:{
      tabs:{mission:'MISSION',route:'ROUTE',cruise:'REISEFLUG',aar:'AAR',bingo:'BINGO / DIVERT',card:'DATA CARD',settings:'EINSTELLUNGEN'},
      labels:{missionName:'Mission',missionType:'Missionstyp',missionNotes:'Missionshinweise',missionPreset:'Optionaler Missions-Preset',aarTankerType:'Tankermuster',aarTankerCallsign:'Tanker-Callsign',aarFrequency:'Frequenz / Status',aarPlannedArct:'ARCT PLAN (Zulu)',aarPlannedOut:'AAR OUT PLAN (Zulu)',divertSelection:'Verwendeter Divert',aircraft:'Flugzeugmuster',callsign:'Callsign',missionDate:'Missionsdatum (UTC)',startZulu:'Missionsstart (Zulu)',departure:'Abflug',depElevation:'Abflughöhe (ft)',arrival:'Ziel',arrElevation:'Zielhöhe (ft)',tankOnBoard:'Tankinhalt / FOB Start (kg)',taxiMin:'Taxi / Ground (min)',reserveKg:'Landereserve (kg)',surchargePct:'Verbrauchszuschlag (%)',simbriefUser:'Pilot ID / Navigraph Alias',cruiseMode:'Berechnungsart',cruiseDistanceSource:'Distanzquelle',cruiseDistance:'Distanz (NM)',cruiseTimeInput:'Gesamtflugzeit (min)',cruiseAltitude:'Reiseflughöhe (ft)',cruiseMach:'Mach',cruiseWind:'Windkomponente (kt)',cruiseDepElev:'Abflughöhe (ft)',cruiseArrElev:'Zielhöhe (ft)',divertAltitude:'Divert-Höhe (ft)',divertMach:'Divert Mach',divertWind:'Windkomponente (kt)',recoveryExtra:'Missed Approach / Recovery extra (kg)',alternate1Search:'Air Base suchen',alternate2Search:'Air Base suchen',alternate1Country:'Land',alternate2Country:'Land',alternate1:'Alternate / ICAO manuell',alternate2:'Alternate / ICAO manuell',divert1ManualDist:'Distanz manuell (NM)',divert2ManualDist:'Distanz manuell (NM)',divert1ManualElev:'Höhe manuell (ft)',divert2ManualElev:'Höhe manuell (ft)',bingoWp:'Bingo-Bezugspunkt',jokerBuffer:'Joker-Puffer über Bingo (kg)',aarDuration:'AAR EVENT DURATION (min)'},
      buttons:{loadMissionPreset:'PRESET LADEN',newManualMission:'NEUE MANUELLE MISSION',loadDemo:'DEMO LADEN',savePilot:'SPEICHERN',importSimbrief:'LETZTEN OFP IMPORTIEREN',addWaypoint:'＋ WAYPOINT HINZUFÜGEN',recalculate:'↻ NEU BERECHNEN',saveMission:'LOKAL SPEICHERN',loadMission:'LOKAL LADEN',cruiseUseMissionAirports:'MIT AKTUELLER MISSION SYNCHRONISIEREN',printCard:'DRUCKEN / ALS PDF SPEICHERN',refreshCard:'AKTUALISIEREN',useArrivalReference:'ARRIVAL VERWENDEN',infoClose:'SCHLIESSEN'},
      misc:{profilesHint:'Weitere Muster lassen sich später als eigenes Profil mit Tankkapazität, Ground/Climb/Descent und eigener Fuel-Flow-Tabelle ergänzen.',displayHeading:'DARSTELLUNG & SPRACHE',themeHint:'Farben ändern nur die Darstellung. Grün/Amber/Rot bleiben für Status- und Warnwerte reserviert.',dataModelHeading:'DATENMODELL',fuelTableLabel:'Fuel-Tabelle',aarDataLabel:'AAR-Messdaten',airportsLabel:'Flugplätze',localSaveLabel:'Lokale Speicherung',localSaveValue:'NUR GERÄT',calculationLabel:'Berechnung',calculationValue:'OFFLINE',airacCycleLabel:'AIRAC-Kalenderzyklus',navdataStatusLabel:'Navdata-Status',securityHeading:'SICHERHEIT & DATENSCHUTZ',securityNoAccount:'Kein App-Konto, keine Werbung und keine Analyse-/Tracking-SDKs.',securityLocal:'Missionen, Einstellungen und Air-Base-Suche bleiben lokal auf diesem Gerät; Suchbegriffe werden nicht übertragen.',securityPermissions:'Die App fordert keinen Zugriff auf Kamera, Mikrofon, Standort, Payment oder USB an.',securitySimbrief:'SimBrief wird nur nach Tippen auf Import kontaktiert. Pilot-ID/Alias wird verwendet; ein SimBrief-Passwort wird weder abgefragt noch gespeichert.',clear:'LOKALE DATEN LÖSCHEN',privacy:'DATENSCHUTZ',securityMessage:'Es wird keine absolute Sicherheitsgarantie versprochen; die App ist bewusst mit wenigen Berechtigungen und externen Abhängigkeiten aufgebaut.',testStatusHeading:'SIMULATION / TESTSTATUS',testStatusText:'Simulator-Modellrechnung auf Basis gemessener und interpolierter Performancedaten. Kein offizielles Flugdokument und nicht für reale Einsatzplanung.'}
    },
    en:{
      tabs:{mission:'MISSION',route:'ROUTE',cruise:'CRUISE',aar:'AAR',bingo:'BINGO / DIVERT',card:'DATA CARD',settings:'SETTINGS'},
      labels:{missionName:'Mission',missionType:'Mission type',missionNotes:'Mission notes',missionPreset:'Optional mission preset',aarTankerType:'Tanker type',aarTankerCallsign:'Tanker callsign',aarFrequency:'Frequency / status',aarPlannedArct:'ARCT PLAN (Zulu)',aarPlannedOut:'AAR OUT PLAN (Zulu)',divertSelection:'Used divert',aircraft:'Aircraft',callsign:'Callsign',missionDate:'Mission date (UTC)',startZulu:'Mission start (Zulu)',departure:'Departure',depElevation:'Departure elevation (ft)',arrival:'Arrival',arrElevation:'Arrival elevation (ft)',tankOnBoard:'Tank on board / Start FOB (kg)',taxiMin:'Taxi / Ground (min)',reserveKg:'Landing reserve (kg)',surchargePct:'Fuel surcharge (%)',simbriefUser:'Pilot ID / Navigraph Alias',cruiseMode:'Calculation mode',cruiseDistanceSource:'Distance source',cruiseDistance:'Distance (NM)',cruiseTimeInput:'Total flight time (min)',cruiseAltitude:'Cruise altitude (ft)',cruiseMach:'Mach',cruiseWind:'Wind component (kt)',cruiseDepElev:'Departure elevation (ft)',cruiseArrElev:'Arrival elevation (ft)',divertAltitude:'Divert altitude (ft)',divertMach:'Divert Mach',divertWind:'Wind component (kt)',recoveryExtra:'Missed approach / Recovery extra (kg)',alternate1Search:'Search air base',alternate2Search:'Search air base',alternate1Country:'Country',alternate2Country:'Country',alternate1:'Alternate / manual ICAO',alternate2:'Alternate / manual ICAO',divert1ManualDist:'Manual distance (NM)',divert2ManualDist:'Manual distance (NM)',divert1ManualElev:'Manual elevation (ft)',divert2ManualElev:'Manual elevation (ft)',bingoWp:'Bingo reference point',jokerBuffer:'Joker buffer over Bingo (kg)',aarDuration:'AAR EVENT DURATION (min)'},
      buttons:{loadMissionPreset:'LOAD PRESET',newManualMission:'NEW MANUAL MISSION',loadDemo:'LOAD DEMO',savePilot:'SAVE',importSimbrief:'IMPORT LATEST OFP',addWaypoint:'＋ ADD WAYPOINT',recalculate:'↻ RECALCULATE',saveMission:'SAVE LOCAL',loadMission:'LOAD LOCAL',cruiseUseMissionAirports:'SYNC WITH CURRENT MISSION',printCard:'PRINT / SAVE PDF',refreshCard:'REFRESH',useArrivalReference:'USE ARRIVAL',infoClose:'CLOSE'},
      misc:{profilesHint:'Additional aircraft can later be added as separate profiles with tank capacity, ground/climb/descent and their own fuel-flow table.',displayHeading:'APPEARANCE & LANGUAGE',themeHint:'Themes only change the display. Green/amber/red remain reserved for status and warning values.',dataModelHeading:'DATA MODEL',fuelTableLabel:'Fuel table',aarDataLabel:'AAR measurements',airportsLabel:'Airports',localSaveLabel:'Local save',localSaveValue:'DEVICE ONLY',calculationLabel:'Calculation',calculationValue:'OFFLINE',airacCycleLabel:'AIRAC calendar cycle',navdataStatusLabel:'Navdata status',securityHeading:'SECURITY & PRIVACY',securityNoAccount:'No app account, no advertising and no analytics/tracking SDKs.',securityLocal:'Mission data, settings and air-base search stay local on this device; search terms are not transmitted.',securityPermissions:'The app does not request camera, microphone, location, payment or USB access.',securitySimbrief:'SimBrief is contacted only when you press Import. Pilot ID/Alias is used; no SimBrief password is requested or stored.',clear:'DELETE LOCAL DATA',privacy:'PRIVACY POLICY',securityMessage:'No absolute security guarantee is claimed; the app is intentionally built with minimal permissions and external dependencies.',testStatusHeading:'SIMULATION / TEST STATUS',testStatusText:'Simulator model calculation using measured and interpolated performance data. Not an official flight document and not for real-world operational planning.'}
    }
  };
  let lang='en';
  function setLabel(id,text){const el=document.getElementById(id);if(!el)return;const lab=el.closest('label');if(!lab)return;let n=[...lab.childNodes].find(x=>x.nodeType===3&&x.textContent.trim());if(n)n.textContent=text;else lab.insertBefore(document.createTextNode(text),lab.firstChild);}
  function set(id,text){const el=document.getElementById(id);if(el)el.textContent=text;}
  function apply(next,persist=true){lang=(next==='en'?'en':'de');if(persist)localStorage.setItem('ife_language',lang);document.documentElement.lang=lang;const c=D[lang];
    document.querySelectorAll('.tab').forEach(b=>{const k=b.dataset.view,sp=b.querySelector('span:last-child');if(sp&&c.tabs[k])sp.textContent=c.tabs[k];});
    Object.entries(c.labels).forEach(([id,v])=>setLabel(id,v));Object.entries(c.buttons).forEach(([id,v])=>set(id,v));
    Object.entries(c.misc).forEach(([id,v])=>set(id,v));
    setLabel('layoutSelect',lang==='de'?'Oberfläche':'Interface layout');
    setLabel('languageSelect',lang==='de'?'Sprache':'Language');
    setLabel('themeSelect',lang==='de'?'Farbe / Tag-Nacht-Theme':'Color / day-night theme');
    const ls=document.getElementById('languageSelect');if(ls)ls.value=lang;
    const title=document.querySelector('#view-mission .sortie-panel h2');if(title)title.textContent=lang==='de'?'EINSATZDATEN':'SORTIE DATA';
    const routeTitle=document.querySelector('#view-route h2');if(routeTitle)routeTitle.textContent=lang==='de'?'ROUTE / LEG-EDITOR':'ROUTE / LEG EDITOR';
    const routeHint=document.querySelector('#view-route .route-title .muted');if(routeHint)routeHint.innerHTML=lang==='de'?'Waypoint → ALT → Mach → Zeit (ETA Z) → NM → Hold/WP OUT. Auf Tablet: Waypoint antippen, Felder öffnen oder schließen. Eingabe mit Enter oder beim Verlassen des Feldes übernehmen. Departure/Arrival und Platzhöhen unter Mission ändern.':'Waypoint → ALT → Mach → time (ETA Z) → NM → hold/WP OUT. On tablets: tap a waypoint to open or close fields. Commit with Enter or by leaving the field. Edit departure/arrival and elevations under Mission.';
    const cruiseTitle=document.querySelector('#view-cruise h2');if(cruiseTitle)cruiseTitle.textContent=lang==='de'?'REISEFLUGRECHNER':'CRUISE CALCULATOR';
    const cruiseHint=document.querySelector('#view-cruise .panel .muted');if(cruiseHint)cruiseHint.textContent=lang==='de'?'Gesamtstrecke oder Gesamtzeit planen. Steig- und Sinkflug sind enthalten.':'Plan total distance or total time. Climb and descent are included.';
    const simHint=document.querySelector('.simbrief-panel .muted');if(simHint)simHint.textContent=lang==='de'?'Letzten OFP importieren. Danach bleiben Datum, Startzeit, Route, Höhe, Mach, Wind und Leg-Zeit editierbar.':'Import the latest OFP. Date, start time, route, altitude, Mach, wind and leg time remain editable afterwards.';
    const cardHint=document.querySelector('#view-card .card-toolbar .muted');if(cardHint)cardHint.textContent=lang==='de'?'Missionskarte aus dem aktuellen App-Zustand':'Mission card generated from the current app state';
    const airacHint=document.getElementById('airacHint');if(airacHint)airacHint.textContent=lang==='de'?'AIRAC zeigt den aktuellen 28-Tage-Kalenderzyklus. Die lokale App-Datenbank wird dadurch nicht als AIRAC-zertifiziert oder vollständig aktuell ausgewiesen.':'AIRAC shows the current 28-day calendar cycle. This does not certify the bundled local database as synchronized to that cycle or fully current.';
    const scroll=document.querySelector('.route-scroll-cue');if(scroll)scroll.textContent=lang==='de'?'↔ horizontal wischen für ETE · Fuel · FOB':'↔ swipe horizontally for ETE · Fuel · FOB';
    const cm=document.getElementById('cruiseMode');if(cm){cm.options[0].textContent=lang==='de'?'DISTANZ (NM)':'DISTANCE (NM)';cm.options[1].textContent=lang==='de'?'GESAMTZEIT (MIN)':'TOTAL TIME (MIN)';}
    const cds=document.getElementById('cruiseDistanceSource');if(cds){cds.options[0].textContent=lang==='de'?'AKTUELLE ROUTE · AUTO':'CURRENT ROUTE · AUTO';cds.options[1].textContent=lang==='de'?'DEP → ARR DIREKT · AUTO':'DEP → ARR DIRECT · AUTO';cds.options[2].textContent=lang==='de'?'DISTANZ MANUELL':'MANUAL DISTANCE';}
    window.dispatchEvent(new CustomEvent('ife-language-changed',{detail:{lang}}));
  }
  function t(de,en){return lang==='en'?en:de;}
  function getLang(){return lang;}
  window.IFE_I18N={apply,t,getLang,D};
})();
